# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb142f5a6f75f00ad8cdddd43d188c72d90ec5eb7c2356c3304473357ec6e3c81bc63458efc0655a9fa5af160d50899c14fb37d9ec6db35379f1c7b8d398483b

test:
  secret_key_base: 78ae7e97fea639365dec63d9963e5ab959ebfa1073ec87dbeca6b877d587a914b1a6d7e13028dab341ae459194aa37aa50b99139658e50498ba8b01a21275481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
